### ISSUE TITLE
Need to create launch.json

### ISSUE THREAD

**Issue by guillaume-haerinck** [JulesFouchy/Simple-Cpp-Setup#1]
We should be able to launch the project by pressing `F5` on both linux and windows

**Comment by JulesFouchy** [comment]
I have never had a use for it since I use the CMake extension (shortcuts are `SHIFT+F5` to run and `CTRL+F5` to debug) but you are right! Would you be kind enough to open a pull request?

**Comment by JulesFouchy** [comment]
I believe using the CMake extension is enough.

**Comment by JulesFouchy** [comment]
I believe using the CMake extension will be enough.
